# 후원 및 지원 방법

github: [w3labkr]  # GitHub Sponsors 사용자명
# patreon: user  # Patreon 사용자명 (사용 시 주석 해제)
# open_collective: project  # Open Collective 프로젝트명 (사용 시 주석 해제)
# ko_fi: user  # Ko-fi 사용자명 (사용 시 주석 해제)
# tidelift: npm/package  # Tidelift 패키지명 (사용 시 주석 해제)
# community_bridge: project  # CommunityBridge 프로젝트명 (사용 시 주석 해제)
# liberapay: user  # Liberapay 사용자명 (사용 시 주석 해제)
# issuehunt: user  # IssueHunt 사용자명 (사용 시 주석 해제)
# otechie: user  # Otechie 사용자명 (사용 시 주석 해제)
# lfx_crowdfunding: project  # LFX Crowdfunding 프로젝트명 (사용 시 주석 해제)
# custom: ['https://paypal.me/username', 'https://buymeacoffee.com/username']  # 커스텀 후원 링크 (사용 시 주석 해제)
