name = "nextjs14-qrcode"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_populate_process_env"]

[env.production]
compatibility_flags = ["nodejs_compat_populate_process_env"]

[env.preview]
compatibility_flags = ["nodejs_compat_populate_process_env"]
